CREATE TABLE public.academic_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL UNIQUE,
  school_name text NOT NULL,
  school_type text NOT NULL CHECK (school_type = ANY (ARRAY['Government'::text, 'Private'::text, 'International'::text, 'Other'::text, 'public'::text, 'private'::text])),
  last_grade_completed text,
  academic_year_completed integer,
  reason_for_leaving text,
  principal_name text,
  school_phone_number text CHECK (school_phone_number IS NULL OR school_phone_number ~ '^\+?[\d\s\-\(\)]+$'::text),
  school_email text,
  school_address text,
  additional_notes text,
  report_card_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_history_pkey PRIMARY KEY (id),
  CONSTRAINT academic_history_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.application_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL UNIQUE,
  document_type text NOT NULL,
  file_url text NOT NULL,
  upload_status text NOT NULL DEFAULT 'completed'::text,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  file_urls ARRAY DEFAULT ARRAY[]::text[],
  document_types ARRAY DEFAULT ARRAY[]::text[],
  file_names ARRAY DEFAULT ARRAY[]::text[],
  upload_timestamps ARRAY DEFAULT ARRAY[]::timestamp with time zone[],
  is_consolidated boolean DEFAULT false,
  CONSTRAINT application_documents_pkey PRIMARY KEY (id),
  CONSTRAINT application_documents_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT application_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'submitted'::text, 'completed'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.declarations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL UNIQUE,
  agree_truth boolean NOT NULL DEFAULT false,
  agree_policies boolean NOT NULL DEFAULT false,
  agree_financial boolean NOT NULL DEFAULT false,
  agree_verification boolean NOT NULL DEFAULT false,
  agree_data_processing boolean NOT NULL DEFAULT false,
  agree_audit_storage boolean NOT NULL DEFAULT false,
  agree_affordability_processing boolean NOT NULL DEFAULT false,
  full_name text,
  city text,
  status text DEFAULT 'completed'::text,
  signed boolean DEFAULT false,
  date_signed date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT declarations_pkey PRIMARY KEY (id),
  CONSTRAINT declarations_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['proof_of_address'::text, 'id_document'::text, 'payslip'::text, 'bank_statement'::text, 'academic_history'::text])),
  file_url text NOT NULL,
  upload_status text NOT NULL DEFAULT 'completed'::text CHECK (upload_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text])),
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.fee_responsibility (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  fee_person text NOT NULL,
  relationship text NOT NULL,
  fee_terms_accepted boolean NOT NULL DEFAULT false,
  selected_plan text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  parent_id_number text,
  parent_first_name text,
  parent_surname text,
  parent_email text,
  parent_mobile text,
  bank_name text,
  branch_code text,
  account_number text,
  account_type text,
  CONSTRAINT fee_responsibility_pkey PRIMARY KEY (id),
  CONSTRAINT fee_responsibility_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.financing_selections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid UNIQUE,
  plan_type text NOT NULL CHECK (plan_type = ANY (ARRAY['monthly_flat'::text, 'termly_discount'::text, 'annual_discount'::text, 'sibling_discount'::text, 'bnpl'::text, 'forward_funding'::text, 'arrears-bnpl'::text])),
  discount_rate numeric,
  cost_of_credit numeric,
  repayment_term text,
  next_of_kin_surname text,
  next_of_kin_first_name text,
  next_of_kin_relationship text,
  next_of_kin_mobile text CHECK (next_of_kin_mobile IS NULL OR next_of_kin_mobile ~ '^\+?[\d\s\-\(\)]+$'::text),
  next_of_kin_email text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT financing_selections_pkey PRIMARY KEY (id),
  CONSTRAINT financing_selections_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.medical_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  medical_aid_name text,
  member_number text,
  main_member_name text,
  conditions ARRAY,
  allergies text,
  doctor_name text,
  doctor_phone_number text CHECK (doctor_phone_number IS NULL OR doctor_phone_number ~ '^\+?[\d\s\-\(\)]+$'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  member_name character varying,
  CONSTRAINT medical_info_pkey PRIMARY KEY (id),
  CONSTRAINT medical_info_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.next_of_kin (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL UNIQUE,
  surname text NOT NULL,
  first_name text NOT NULL,
  id_number text,
  relationship text NOT NULL CHECK (relationship = ANY (ARRAY['PARENT'::text, 'SPOUSE'::text, 'SIBLING'::text, 'AUNT'::text, 'UNCLE'::text, 'COUSIN'::text, 'GRANDPARENT'::text, 'GUARDIAN'::text, 'FRIEND'::text, 'OTHER'::text, 'Mother'::text, 'Father'::text, 'Brother'::text, 'Sister'::text, 'Aunt'::text, 'Uncle'::text, 'Grandmother'::text, 'Grandfather'::text, 'Cousin'::text, 'Guardian'::text, 'Other'::text])),
  mobile_number text NOT NULL CHECK (mobile_number IS NOT NULL AND mobile_number ~ '^\+?[0-9\s\-\(\)]+$'::text),
  email_address text NOT NULL CHECK (email_address IS NOT NULL AND email_address ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'::text),
  phone_number text,
  alternate_mobile text,
  physical_address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT next_of_kin_pkey PRIMARY KEY (id),
  CONSTRAINT next_of_kin_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.parents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  relationship text NOT NULL,
  surname text NOT NULL,
  first_name text NOT NULL,
  id_number text CHECK (id_number IS NULL OR id_number ~ '^\d{13}$'::text),
  email text CHECK (email IS NULL OR email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'::text),
  mobile text CHECK (mobile IS NULL OR mobile ~ '^\+?[\d\s\-\(\)]+$'::text),
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT parents_pkey PRIMARY KEY (id),
  CONSTRAINT parents_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  amount_paid numeric NOT NULL,
  amount numeric,
  payment_date date NOT NULL,
  completed_at timestamp with time zone,
  payment_status character varying NOT NULL DEFAULT 'Paid'::character varying CHECK (payment_status::text = ANY (ARRAY['Paid'::character varying, 'Outstanding'::character varying, 'Partial'::character varying, 'Pending'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  payment_method character varying,
  reference_number character varying,
  reference character varying UNIQUE,
  plan_type character varying,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  student_id uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  surname text NOT NULL,
  first_name text NOT NULL,
  middle_name text,
  preferred_name text,
  date_of_birth date NOT NULL,
  gender text NOT NULL CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'prefer_not_to_say'::text])),
  home_language text NOT NULL,
  id_number text NOT NULL UNIQUE CHECK (id_number ~ '^\d{13}$'::text),
  previous_grade text,
  grade_applied_for text,
  previous_school text,
  email text,
  phone text CHECK (phone IS NULL OR phone ~ '^\+?[\d\s\-\(\)]+$'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  monthly_fee numeric DEFAULT 5000.00,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.uploaded_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  filename text NOT NULL,
  original_filename text NOT NULL,
  file_size bigint NOT NULL,
  content_type text NOT NULL,
  document_type text NOT NULL,
  bucket_name text NOT NULL,
  file_path text NOT NULL,
  download_url text NOT NULL,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT uploaded_files_pkey PRIMARY KEY (id),
  CONSTRAINT uploaded_files_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT uploaded_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);